package deck

var suits = []string{
	"Clubs",
	"Diamonds",
	"Spades",
	"Hearts",
}

var names = []string{
	"Ace",
	"Two",
	"Three",
	"Four",
	"Five",
	"Six",
	"Seven",
	"Eight",
	"Nine",
	"Ten",
	"Jack",
	"Queen",
	"King",
}

var glyphs = map[string]string{
	"Ace of Spades":     "🂡",
	"Ace of Hearts":     "🂱",
	"Ace of Diamonds":   "🃁",
	"Ace of Clubs":      "🃑",
	"Two of Spades":     "🂢",
	"Two of Hearts":     "🂲",
	"Two of Diamonds":   "🃂",
	"Two of Clubs":      "🃒",
	"Three of Spades":   "🂣",
	"Three of Hearts":   "🂳",
	"Three of Diamonds": "🃃",
	"Three of Clubs":    "🃓",
	"Four of Spades":    "🂤",
	"Four of Hearts":    "🂴",
	"Four of Diamonds":  "🃄",
	"Four of Clubs":     "🃔",
	"Five of Spades":    "🂥",
	"Five of Hearts":    "🂵",
	"Five of Diamonds":  "🃅",
	"Five of Clubs":     "🃕",
	"Six of Spades":     "🂦",
	"Six of Hearts":     "🂶",
	"Six of Diamonds":   "🃆",
	"Six of Clubs":      "🃖",
	"Seven of Spades":   "🂧",
	"Seven of Hearts":   "🂷",
	"Seven of Diamonds": "🃇",
	"Seven of Clubs":    "🃗",
	"Eight of Spades":   "🂨",
	"Eight of Hearts":   "🂸",
	"Eight of Diamonds": "🃈",
	"Eight of Clubs":    "🃘",
	"Nine of Spades":    "🂩",
	"Nine of Hearts":    "🂹",
	"Nine of Diamonds":  "🃉",
	"Nine of Clubs":     "🃙",
	"Ten of Spades":     "🂪",
	"Ten of Hearts":     "🂺",
	"Ten of Diamonds":   "🃊",
	"Ten of Clubs":      "🃚",
	"Jack of Spades":    "🂫",
	"Jack of Hearts":    "🂻",
	"Jack of Diamonds":  "🃋",
	"Jack of Clubs":     "🃛",
	"Queen of Spades":   "🂭",
	"Queen of Hearts":   "🂽",
	"Queen of Diamonds": "🃍",
	"Queen of Clubs":    "🃝",
	"King of Spades":    "🂮",
	"King of Hearts":    "🂾",
	"King of Diamonds":  "🃎",
	"King of Clubs":     "🃞",
	"Back":              "🂠",
}
